services:
  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile.dev
    environment:
      - PORT=${INDEXER_SERVICE_PORT}
      - NODE_ENV=${NODE_ENV}
      - SUI_RPC_URL=${SUI_RPC_URL}
      - POLLING_INTERVAL=${POLLING_INTERVAL}
      - BATCH_SIZE=${BATCH_SIZE}
    ports:
      - "${INDEXER_SERVICE_PORT}:${INDEXER_SERVICE_PORT}"
    volumes:
      - ./indexer:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - SUI_RPC_URL=${SUI_RPC_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${BACKEND_SERVICE_PORT}
      - CORS_ORIGIN=${BACKEND_SERVICE_CORS_ORIGIN}
      - REDIS_URL=redis://redis:${REDIS_PORT:-6379}
    ports:
      - "${BACKEND_SERVICE_PORT}:${BACKEND_SERVICE_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Frontend application
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "${FRONTEND_SERVICE_PORT}:${FRONTEND_SERVICE_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_SUI_RPC_URL=${SUI_RPC_URL}
      # - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: