services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sui_airbnb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./indexer:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  # Frontend application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_SUI_RPC_URL=http://host.docker.internal:44340
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  postgres_data:
  sui_data: