FROM node:18-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    libssl1.1 \
    netcat \
    && rm -rf /var/lib/apt/lists/*

# Copy package files
COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

COPY . .

RUN mkdir -p dist

RUN chmod +x start.sh

EXPOSE 4000

CMD ["/bin/sh", "start.sh"]

